import { ApiError, api } from "./api.js";
import type { GraphVersion, ProjectRole } from "./graph-helpers.js";
import { buildSnapshotRequest, canCreateSnapshot } from "./snapshot-helpers.js";

type Project = { id: string; role: ProjectRole };
type Options = { onUnauthorized(): void };
type Artifact = {
  id: string;
  name: string;
  type: string;
  currentVersion: number;
  freshness: { state: string };
};
type Snapshot = {
  id: string;
  projectId: string;
  name: string;
  gitSha: string;
  artifactCount: number;
  createdBy: string;
  createdAt: string;
  graph: {
    version: number;
    sourceCommitSha: string;
    storageLayout: string;
    publicationId: string | null;
    publishedAttempt: number;
    publishedLeaseId: string;
    uploadId: string;
    checksum: string;
    byteSize: number;
    contentType: string;
    repository: {
      provider: string;
      providerRepositoryId: string;
      owner: string;
      name: string;
      canonicalUrl: string;
    };
    graphifyVersion: string;
    adapterVersion: string;
    profile: string;
    formatVersion: number;
    generator: string;
    generatedBy: string;
    generatedAt: string;
  };
  manifest: { checksum: string; byteSize: number; contentType: string };
};
export type SnapshotArtifactProvenance = {
  artifactId: string;
  version: number;
  type: string;
  checksum: string;
  byteSize: number;
  contentType: string;
  uploadId: string;
  sourceCommitSha: string | null;
  changeNote: string | null;
  createdBy: string;
  createdAt: string;
};
type SnapshotDetail = { snapshot: Snapshot; artifacts: SnapshotArtifactProvenance[] };

export const SNAPSHOT_GRAPH_PROVENANCE_FIELDS = [
  "version",
  "sourceCommitSha",
  "storageLayout",
  "publicationId",
  "publishedAttempt",
  "publishedLeaseId",
  "uploadId",
  "checksum",
  "byteSize",
  "contentType",
  "repository.provider",
  "repository.providerRepositoryId",
  "repository.owner",
  "repository.name",
  "repository.canonicalUrl",
  "graphifyVersion",
  "adapterVersion",
  "profile",
  "formatVersion",
  "generator",
  "generatedBy",
  "generatedAt",
] as const;
export const SNAPSHOT_ARTIFACT_PROVENANCE_FIELDS = [
  "artifactId",
  "version",
  "type",
  "checksum",
  "byteSize",
  "contentType",
  "uploadId",
  "sourceCommitSha",
  "changeNote",
  "createdBy",
  "createdAt",
] as const;
export const SNAPSHOT_MANIFEST_PROVENANCE_FIELDS = ["checksum", "byteSize", "contentType"] as const;

function element<K extends keyof HTMLElementTagNameMap>(
  tag: K,
  className?: string,
  text?: string,
): HTMLElementTagNameMap[K] {
  const node = document.createElement(tag);
  if (className) node.className = className;
  if (text !== undefined) node.textContent = text;
  return node;
}

function detail(label: string, value: string): HTMLDivElement {
  const row = element("div", "snapshot-detail");
  row.append(element("dt", undefined, label), element("dd", undefined, value));
  return row;
}

function shown(value: string | number | null): string {
  return value === null ? "Not recorded" : String(value);
}

export function snapshotGraphProvenanceRows(graph: Snapshot["graph"]): Array<[string, string]> {
  return [
    ["Graph version", shown(graph.version)],
    ["Graph source commit", graph.sourceCommitSha],
    ["Storage layout", graph.storageLayout],
    ["Publication ID", shown(graph.publicationId)],
    ["Published attempt", shown(graph.publishedAttempt)],
    ["Published lease ID", graph.publishedLeaseId],
    ["Graph upload ID", graph.uploadId],
    ["Graph checksum", graph.checksum],
    ["Graph bytes", shown(graph.byteSize)],
    ["Graph content type", graph.contentType],
    ["Repository provider", graph.repository.provider],
    ["Provider repository ID", graph.repository.providerRepositoryId],
    ["Repository owner", graph.repository.owner],
    ["Repository name", graph.repository.name],
    ["Repository URL", graph.repository.canonicalUrl],
    ["Graphify version", graph.graphifyVersion],
    ["Adapter version", graph.adapterVersion],
    ["Build profile", graph.profile],
    ["Graph format version", shown(graph.formatVersion)],
    ["Generator", graph.generator],
    ["Generated by", graph.generatedBy],
    ["Generated at", graph.generatedAt],
  ];
}

export function snapshotArtifactProvenanceRows(
  artifact: SnapshotArtifactProvenance,
): Array<[string, string]> {
  return [
    ["Artifact ID", artifact.artifactId],
    ["Artifact version", shown(artifact.version)],
    ["Artifact type", artifact.type],
    ["Artifact checksum", artifact.checksum],
    ["Artifact bytes", shown(artifact.byteSize)],
    ["Artifact content type", artifact.contentType],
    ["Artifact upload ID", artifact.uploadId],
    ["Artifact source commit", shown(artifact.sourceCommitSha)],
    ["Change note", shown(artifact.changeNote)],
    ["Artifact created by", artifact.createdBy],
    ["Artifact created at", artifact.createdAt],
  ];
}

export function snapshotManifestProvenanceRows(
  manifest: Snapshot["manifest"],
): Array<[string, string]> {
  return [
    ["Manifest checksum", manifest.checksum],
    ["Manifest bytes", shown(manifest.byteSize)],
    ["Manifest content type", manifest.contentType],
  ];
}

export function mountSnapshots(host: HTMLElement, project: Project, options: Options): () => void {
  let generation = 0;
  const controller = new AbortController();
  let cursor: string | null = null;
  let artifacts: Artifact[] = [];
  let graphs: GraphVersion[] = [];
  const canCreate = canCreateSnapshot(project.role);
  const shell = element("section", "snapshots-view reveal");
  shell.setAttribute("aria-labelledby", "snapshots-title");
  const heading = element("header", "snapshot-heading");
  const headingCopy = element("div");
  const title = element("h1", undefined, "Snapshots");
  title.id = "snapshots-title";
  headingCopy.append(element("p", "kicker", "Exact reproducibility / immutable"), title);
  heading.append(
    headingCopy,
    element("p", "read-only-note", canCreate ? "Admin + editor creation" : "Viewer / read only"),
  );
  const status = element("p", "activity-status", "Loading verified snapshots...");
  status.setAttribute("role", "status");
  const createRegion = element("div");
  const list = element("div", "snapshot-list");
  const more = element("button", "secondary-action", "Load older snapshots");
  more.type = "button";
  more.hidden = true;
  const inspect = element("div");
  shell.append(heading, status, createRegion, list, more, inspect);
  host.replaceChildren(shell);

  function handleError(cause: unknown, fallback: string): void {
    if (cause instanceof ApiError && cause.status === 401) options.onUnauthorized();
    else if (status)
      status.textContent =
        cause instanceof ApiError && cause.status === 404
          ? "Snapshots are unavailable for this project."
          : fallback;
  }

  async function load(append = false): Promise<void> {
    const requestGeneration = ++generation;
    if (!status || !list || !more) return;
    status.textContent = append
      ? "Loading older verified snapshots..."
      : "Loading verified snapshots...";
    more.disabled = true;
    const query = new URLSearchParams({ limit: "25" });
    if (append && cursor) query.set("cursor", cursor);
    try {
      const page = await api<{ snapshots: Snapshot[]; nextCursor: string | null }>(
        `/projects/${project.id}/snapshots?${query}`,
        { signal: controller.signal },
      );
      if (requestGeneration !== generation || controller.signal.aborted) return;
      if (!append) list.replaceChildren();
      for (const snapshot of page.snapshots) list.append(snapshotRow(snapshot));
      cursor = page.nextCursor;
      more.hidden = cursor === null;
      status.textContent = list.childElementCount
        ? `${list.childElementCount} integrity-verified snapshot${list.childElementCount === 1 ? "" : "s"} shown.`
        : "No snapshots have been created.";
    } catch (cause) {
      if (!controller.signal.aborted && requestGeneration === generation)
        handleError(cause, "Snapshots could not be verified and loaded.");
    } finally {
      if (requestGeneration === generation) more.disabled = false;
    }
  }

  function snapshotRow(snapshot: Snapshot): HTMLButtonElement {
    const row = element("button", "snapshot-row");
    row.type = "button";
    row.setAttribute("aria-label", `Inspect snapshot ${snapshot.name}`);
    row.append(
      element("strong", undefined, snapshot.name),
      element(
        "span",
        undefined,
        `Graph v${snapshot.graph.version} / ${snapshot.artifactCount} artifacts`,
      ),
      element("time", undefined, new Date(snapshot.createdAt).toLocaleString()),
    );
    row.addEventListener("click", () => void inspectSnapshot(snapshot.id, row));
    return row;
  }

  async function inspectSnapshot(id: string, source: HTMLElement): Promise<void> {
    const requestGeneration = ++generation;
    if (!inspect || !status) return;
    status.textContent = "Verifying exact snapshot provenance...";
    try {
      const reply = await api<SnapshotDetail>(`/projects/${project.id}/snapshots/${id}`, {
        signal: controller.signal,
      });
      if (requestGeneration !== generation || controller.signal.aborted) return;
      inspect.replaceChildren();
      const section = element("section", "snapshot-inspector");
      section.tabIndex = -1;
      section.append(
        element("p", "kicker", "Verified immutable provenance"),
        element("h2", undefined, reply.snapshot.name),
      );
      const details = element("dl", "snapshot-detail-grid");
      const snapshotRows: Array<[string, string]> = [
        ["Snapshot ID", reply.snapshot.id],
        ["Project ID", reply.snapshot.projectId],
        ["Git commit", reply.snapshot.gitSha],
        ["Artifact count", shown(reply.snapshot.artifactCount)],
        ["Snapshot created by", reply.snapshot.createdBy],
        ["Snapshot created at", reply.snapshot.createdAt],
        ...snapshotGraphProvenanceRows(reply.snapshot.graph),
        ...snapshotManifestProvenanceRows(reply.snapshot.manifest),
      ];
      for (const [label, value] of snapshotRows) details.append(detail(label, value));
      section.append(details, element("h3", undefined, "Sealed artifacts"));
      const refs = element("div", "snapshot-references");
      if (!reply.artifacts.length)
        refs.append(element("p", undefined, "No artifacts were selected."));
      for (const artifact of reply.artifacts) {
        const artifactDetails = element("dl", "snapshot-artifact-provenance");
        for (const [label, value] of snapshotArtifactProvenanceRows(artifact)) {
          artifactDetails.append(detail(label, value));
        }
        refs.append(artifactDetails);
      }
      section.append(refs);
      inspect.append(section);
      status.textContent = "Snapshot integrity and exact provenance verified.";
      queueMicrotask(() => section.focus());
    } catch (cause) {
      if (!controller.signal.aborted && requestGeneration === generation) {
        handleError(cause, "Snapshot integrity verification failed. No provenance is shown.");
        source.focus();
      }
    }
  }

  async function prepareCreate(): Promise<void> {
    if (!canCreate || !createRegion) return;
    try {
      const [artifactPage, graphPage] = await Promise.all([
        api<{ artifacts: Artifact[] }>(`/projects/${project.id}/artifacts?limit=100`, {
          signal: controller.signal,
        }),
        api<{ graphs: GraphVersion[] }>(`/projects/${project.id}/graphs`, {
          signal: controller.signal,
        }),
      ]);
      if (controller.signal.aborted) return;
      artifacts = artifactPage.artifacts;
      graphs = graphPage.graphs.filter(
        (graph) => graph.status === "READY" || graph.status === "SUPERSEDED",
      );
      renderCreate();
    } catch (cause) {
      if (!controller.signal.aborted)
        handleError(cause, "Snapshot creation references could not be loaded.");
    }
  }

  function renderCreate(): void {
    if (!createRegion) return;
    const panel = element("details", "snapshot-create");
    const summary = element("summary", undefined, "Create an exact snapshot");
    const form = element("form", "snapshot-form");
    const nameLabel = element("label", undefined, "Snapshot name");
    const name = element("input");
    name.name = "name";
    name.required = true;
    name.maxLength = 200;
    nameLabel.append(name);
    const graphLabel = element("label", undefined, "Graph version and Git commit");
    const graph = element("select");
    graph.name = "graph";
    graph.required = true;
    graph.append(
      new Option(graphs.length ? "Choose a verified graph" : "No READY graph available", ""),
    );
    for (const item of graphs)
      graph.append(
        new Option(
          `v${item.version} / ${item.status} / ${item.sourceCommitSha}`,
          String(item.version),
        ),
      );
    graphLabel.append(graph);
    const artifactsField = element("fieldset", "snapshot-artifact-options");
    artifactsField.append(
      element("legend", undefined, "Current active artifact versions (optional)"),
    );
    if (!artifacts.length)
      artifactsField.append(element("p", undefined, "No active artifacts are available."));
    for (const artifact of artifacts) {
      const label = element("label");
      const checkbox = element("input");
      checkbox.type = "checkbox";
      checkbox.name = "artifact";
      checkbox.value = artifact.id;
      label.append(
        checkbox,
        document.createTextNode(
          `${artifact.name} / ${artifact.type} / v${artifact.currentVersion} / ${artifact.freshness.state}`,
        ),
      );
      artifactsField.append(label);
    }
    const feedback = element("p", "form-error");
    feedback.setAttribute("aria-live", "polite");
    const submit = element("button", "primary-action", "Create immutable snapshot");
    submit.type = "submit";
    submit.disabled = graphs.length === 0;
    form.append(nameLabel, graphLabel, artifactsField, feedback, submit);
    form.addEventListener("submit", (event) => {
      event.preventDefault();
      void createSnapshot(form, feedback, submit);
    });
    panel.append(summary, form);
    createRegion.replaceChildren(panel);
  }

  async function createSnapshot(
    form: HTMLFormElement,
    feedback: HTMLElement,
    submit: HTMLButtonElement,
  ): Promise<void> {
    const selectedVersion = Number(new FormData(form).get("graph"));
    const selectedGraph = graphs.find((graph) => graph.version === selectedVersion);
    if (!selectedGraph) {
      feedback.textContent = "Choose a READY or historical SUPERSEDED graph.";
      return;
    }
    const selectedIds = new Set(new FormData(form).getAll("artifact").map(String));
    const requestGeneration = ++generation;
    submit.disabled = true;
    feedback.textContent = "Verifying references and publishing the immutable manifest...";
    try {
      const reply = await api<{ snapshot: Snapshot }>(`/projects/${project.id}/snapshots`, {
        method: "POST",
        signal: controller.signal,
        body: JSON.stringify(
          buildSnapshotRequest(
            String(new FormData(form).get("name") ?? ""),
            selectedGraph,
            artifacts,
            selectedIds,
            crypto.randomUUID(),
          ),
        ),
      });
      if (requestGeneration !== generation || controller.signal.aborted) return;
      feedback.textContent = "Snapshot created and integrity verified.";
      form.reset();
      cursor = null;
      await load(false);
      await inspectSnapshot(reply.snapshot.id, submit);
    } catch (cause) {
      if (requestGeneration !== generation || controller.signal.aborted) return;
      if (cause instanceof ApiError && cause.status === 401) return options.onUnauthorized();
      feedback.textContent =
        cause instanceof ApiError && cause.status === 409
          ? "The creation key conflicted. Submit again to use a new key."
          : cause instanceof ApiError && cause.status === 400
            ? "A selected graph or artifact reference is no longer valid. Refresh this view."
            : "Snapshot creation failed without publishing a partial result.";
    } finally {
      if (!controller.signal.aborted) submit.disabled = graphs.length === 0;
    }
  }

  more?.addEventListener("click", () => void load(true));
  void load();
  void prepareCreate();
  return () => {
    ++generation;
    controller.abort();
  };
}
