export type RouteAuthorization =
  | "PUBLIC"
  | "HUMAN_SESSION"
  | "DIRECT_PROJECT_MEMBER"
  | "EXACT_INVITEE"
  | "MCP_PRINCIPAL"
  | "MACHINE_PRINCIPAL";

export type RouteContract = {
  id: string;
  path: RegExp;
  pathShape: string;
  methods: readonly string[];
  handler: string;
  authorization: RouteAuthorization;
};

const route = (
  id: string,
  path: RegExp,
  pathShape: string,
  methods: readonly string[],
  handler: string,
  authorization: RouteAuthorization,
): RouteContract =>
  Object.freeze({ id, path, pathShape, methods: Object.freeze(methods), handler, authorization });

/** The dispatcher consumes this finite contract before invoking a route handler. */
export const ROUTE_CONTRACTS = Object.freeze([
  route("health", /^\/api\/health$/, "/api/health", ["GET"], "health", "PUBLIC"),
  route("github-login", /^\/auth\/github$/, "/auth/github", ["GET"], "beginGithub", "PUBLIC"),
  route(
    "github-callback",
    /^\/auth\/github\/callback$/,
    "/auth/github/callback",
    ["GET"],
    "githubCallback",
    "PUBLIC",
  ),
  route(
    "github-app-setup",
    /^\/auth\/github-app\/setup$/,
    "/auth/github-app/setup",
    ["GET"],
    "githubAppSetup",
    "HUMAN_SESSION",
  ),
  route(
    "github-app-callback",
    /^\/auth\/github-app\/callback$/,
    "/auth/github-app/callback",
    ["GET"],
    "githubAppCallback",
    "HUMAN_SESSION",
  ),
  route("session", /^\/auth\/session$/, "/auth/session", ["GET"], "session", "PUBLIC"),
  route("logout", /^\/auth\/logout$/, "/auth/logout", ["POST"], "logout", "PUBLIC"),
  route(
    "workspaces",
    /^\/workspaces$/,
    "/workspaces",
    ["GET", "POST"],
    "workspaces",
    "HUMAN_SESSION",
  ),
  route("projects", /^\/projects$/, "/projects", ["GET", "POST"], "projects", "HUMAN_SESSION"),
  route(
    "project-resolve",
    /^\/projects\/resolve$/,
    "/projects/resolve",
    ["GET"],
    "resolveProject",
    "HUMAN_SESSION",
  ),
  route(
    "project-detail",
    /^\/projects\/[^/]+$/,
    "/projects/:projectId",
    ["GET", "PATCH"],
    "projectDetail|handleProjectAdministration",
    "DIRECT_PROJECT_MEMBER",
  ),
  route(
    "git",
    /^\/projects\/[^/]+\/git$/,
    "/projects/:projectId/git",
    ["GET", "POST", "DELETE"],
    "beginGitConnection|handleGitConnection",
    "DIRECT_PROJECT_MEMBER",
  ),
  route(
    "git-sync",
    /^\/projects\/[^/]+\/git\/sync$/,
    "/projects/:projectId/git/sync",
    ["POST"],
    "handleGitConnection",
    "DIRECT_PROJECT_MEMBER",
  ),
  route(
    "artifacts",
    /^\/projects\/[^/]+\/artifacts$/,
    "/projects/:projectId/artifacts",
    ["GET", "POST"],
    "handleArtifactRoute",
    "DIRECT_PROJECT_MEMBER",
  ),
  route(
    "artifact",
    /^\/projects\/[^/]+\/artifacts\/[^/]+$/,
    "/projects/:projectId/artifacts/:artifactId",
    ["GET", "DELETE"],
    "handleArtifactRoute",
    "DIRECT_PROJECT_MEMBER",
  ),
  route(
    "artifact-versions",
    /^\/projects\/[^/]+\/artifacts\/[^/]+\/versions$/,
    "/projects/:projectId/artifacts/:artifactId/versions",
    ["GET", "POST"],
    "handleArtifactRoute",
    "DIRECT_PROJECT_MEMBER",
  ),
  route(
    "artifact-version",
    /^\/projects\/[^/]+\/artifacts\/[^/]+\/versions\/[^/]+$/,
    "/projects/:projectId/artifacts/:artifactId/versions/:version",
    ["GET"],
    "handleArtifactRoute",
    "DIRECT_PROJECT_MEMBER",
  ),
  route(
    "graphs",
    /^\/projects\/[^/]+\/graphs$/,
    "/projects/:projectId/graphs",
    ["GET"],
    "handleGraphRoute",
    "DIRECT_PROJECT_MEMBER",
  ),
  route(
    "graph-latest",
    /^\/projects\/[^/]+\/graphs\/latest$/,
    "/projects/:projectId/graphs/latest",
    ["GET"],
    "handleGraphRoute",
    "DIRECT_PROJECT_MEMBER",
  ),
  route(
    "graph-build",
    /^\/projects\/[^/]+\/graphs\/build$/,
    "/projects/:projectId/graphs/build",
    ["POST"],
    "handleGraphRoute",
    "DIRECT_PROJECT_MEMBER",
  ),
  route(
    "graph",
    /^\/projects\/[^/]+\/graphs\/[^/]+$/,
    "/projects/:projectId/graphs/:version",
    ["GET"],
    "handleGraphRoute",
    "DIRECT_PROJECT_MEMBER",
  ),
  route(
    "graph-query",
    /^\/projects\/[^/]+\/graphs\/[^/]+\/query$/,
    "/projects/:projectId/graphs/:version/query",
    ["POST"],
    "handleGraphRoute",
    "DIRECT_PROJECT_MEMBER",
  ),
  route(
    "context-search",
    /^\/projects\/[^/]+\/context\/search$/,
    "/projects/:projectId/context/search",
    ["POST"],
    "handleContextRoute",
    "DIRECT_PROJECT_MEMBER",
  ),
  route(
    "cross-project-context",
    /^\/context\/cross-project\/search$/,
    "/context/cross-project/search",
    ["POST"],
    "handleCrossProjectContextRoute",
    "HUMAN_SESSION",
  ),
  route(
    "sync",
    /^\/projects\/[^/]+\/sync$/,
    "/projects/:projectId/sync",
    ["GET"],
    "handleSyncRoute",
    "DIRECT_PROJECT_MEMBER",
  ),
  route(
    "sync-graph",
    /^\/projects\/[^/]+\/sync\/graph\/[^/]+$/,
    "/projects/:projectId/sync/graph/:version",
    ["GET"],
    "handleSyncRoute",
    "DIRECT_PROJECT_MEMBER",
  ),
  route(
    "sync-states",
    /^\/projects\/[^/]+\/sync-states$/,
    "/projects/:projectId/sync-states",
    ["GET"],
    "handleSyncStateRead",
    "DIRECT_PROJECT_MEMBER",
  ),
  route(
    "sync-state-current",
    /^\/projects\/[^/]+\/sync-states\/current$/,
    "/projects/:projectId/sync-states/current",
    ["GET", "PUT"],
    "handleSyncStateRead|handleSyncStateWrite",
    "DIRECT_PROJECT_MEMBER",
  ),
  route(
    "team",
    /^\/projects\/[^/]+\/team$/,
    "/projects/:projectId/team",
    ["GET", "POST"],
    "handleTeamRoute",
    "DIRECT_PROJECT_MEMBER",
  ),
  route(
    "team-invitation",
    /^\/projects\/[^/]+\/team\/invitations\/[^/]+$/,
    "/projects/:projectId/team/invitations/:invitationId",
    ["DELETE"],
    "handleTeamRoute",
    "DIRECT_PROJECT_MEMBER",
  ),
  route(
    "team-member",
    /^\/projects\/[^/]+\/team\/members\/[^/]+$/,
    "/projects/:projectId/team/members/:userId",
    ["PATCH", "DELETE"],
    "handleTeamRoute",
    "DIRECT_PROJECT_MEMBER",
  ),
  route(
    "invitations",
    /^\/invitations$/,
    "/invitations",
    ["GET"],
    "handleInvitationInbox",
    "HUMAN_SESSION",
  ),
  route(
    "invitation-accept",
    /^\/invitations\/[^/]+\/accept$/,
    "/invitations/:invitationId/accept",
    ["POST"],
    "handleInvitationInbox",
    "EXACT_INVITEE",
  ),
  route(
    "snapshots",
    /^\/projects\/[^/]+\/snapshots$/,
    "/projects/:projectId/snapshots",
    ["GET", "POST"],
    "handleSnapshotRoute",
    "DIRECT_PROJECT_MEMBER",
  ),
  route(
    "snapshot",
    /^\/projects\/[^/]+\/snapshots\/[^/]+$/,
    "/projects/:projectId/snapshots/:snapshotId",
    ["GET"],
    "handleSnapshotRoute",
    "DIRECT_PROJECT_MEMBER",
  ),
  route(
    "snapshot-manifest",
    /^\/projects\/[^/]+\/snapshots\/[^/]+\/manifest$/,
    "/projects/:projectId/snapshots/:snapshotId/manifest",
    ["GET"],
    "handleSnapshotRoute",
    "DIRECT_PROJECT_MEMBER",
  ),
  route(
    "project-metrics",
    /^\/projects\/[^/]+\/metrics$/,
    "/projects/:projectId/metrics",
    ["GET"],
    "handleMetricsRoute",
    "DIRECT_PROJECT_MEMBER",
  ),
  route(
    "project-activity",
    /^\/projects\/[^/]+\/activity$/,
    "/projects/:projectId/activity",
    ["GET"],
    "handleActivityRoute",
    "DIRECT_PROJECT_MEMBER",
  ),
  route(
    "project-activity-detail",
    /^\/projects\/[^/]+\/activity\/[^/]+$/,
    "/projects/:projectId/activity/:eventId",
    ["GET"],
    "handleActivityRoute",
    "DIRECT_PROJECT_MEMBER",
  ),
  route(
    "global-activity",
    /^\/activity$/,
    "/activity",
    ["GET"],
    "handleGlobalActivity",
    "HUMAN_SESSION",
  ),
  route("settings", /^\/settings$/, "/settings", ["GET"], "handleGlobalSettings", "HUMAN_SESSION"),
  route(
    "machine-credentials",
    /^\/projects\/[^/]+\/machine-credentials$/,
    "/projects/:projectId/machine-credentials",
    ["GET", "POST"],
    "handleCredentialRoute",
    "DIRECT_PROJECT_MEMBER",
  ),
  route(
    "machine-credential-rotate",
    /^\/projects\/[^/]+\/machine-credentials\/[^/]+\/rotate$/,
    "/projects/:projectId/machine-credentials/:credentialId/rotate",
    ["POST"],
    "handleCredentialRoute",
    "DIRECT_PROJECT_MEMBER",
  ),
  route(
    "machine-credential",
    /^\/projects\/[^/]+\/machine-credentials\/[^/]+$/,
    "/projects/:projectId/machine-credentials/:credentialId",
    ["DELETE"],
    "handleCredentialRoute",
    "DIRECT_PROJECT_MEMBER",
  ),
  route(
    "machine-graph-command",
    /^\/machine\/projects\/[^/]+\/graphs\/[^/]+\/(claim|fail)$/,
    "/machine/projects/:projectId/graphs/:version/:claim-or-fail",
    ["POST"],
    "handleMachineGraphRoute",
    "MACHINE_PRINCIPAL",
  ),
  route(
    "machine-graph-publish",
    /^\/machine\/projects\/[^/]+\/graphs\/[^/]+\/publish$/,
    "/machine/projects/:projectId/graphs/:version/publish",
    ["PUT"],
    "handleMachineGraphRoute",
    "MACHINE_PRINCIPAL",
  ),
  route(
    "mcp-credentials",
    /^\/mcp-credentials$/,
    "/mcp-credentials",
    ["GET", "POST"],
    "handleMcpCredentialRoute",
    "HUMAN_SESSION",
  ),
  route(
    "mcp-credential-rotate",
    /^\/mcp-credentials\/[^/]+\/rotate$/,
    "/mcp-credentials/:credentialId/rotate",
    ["POST"],
    "handleMcpCredentialRoute",
    "HUMAN_SESSION",
  ),
  route(
    "mcp-credential",
    /^\/mcp-credentials\/[^/]+$/,
    "/mcp-credentials/:credentialId",
    ["DELETE"],
    "handleMcpCredentialRoute",
    "HUMAN_SESSION",
  ),
  route("mcp", /^\/mcp$/, "/mcp", ["GET", "POST"], "handleMcpRoute", "MCP_PRINCIPAL"),
] as const);

export function matchRouteContract(pathname: string): RouteContract | null {
  return ROUTE_CONTRACTS.find((contract) => contract.path.test(pathname)) ?? null;
}
