export const METRIC_STATUSES = [
  "MEASURED_LOCAL",
  "DERIVABLE",
  "BLOCKED_LIVE",
  "MANUAL_STUDY",
  "NOT_COLLECTED",
] as const;

export type MetricStatus = (typeof METRIC_STATUSES)[number];
export type MetricDimension = {
  key: keyof typeof METRIC_DIMENSION_VALUES;
  values: readonly string[];
};
export type MetricDefinition = {
  id: string;
  name: string;
  formula: string;
  numerator: string;
  denominator: string;
  unit: string;
  window: string;
  inclusion: string;
  exclusion: string;
  source: string;
  privacy: string;
  dimensions: readonly MetricDimension[];
  retention: string;
  collection: string;
  baseline: string;
  target: string;
  threshold: string;
  cadence: string;
  owner: string;
  status: MetricStatus;
  requirementSources: readonly string[];
};

type BaseMetric = Omit<
  MetricDefinition,
  "numerator" | "denominator" | "window" | "dimensions" | "requirementSources"
> & { dimensions: readonly (keyof typeof METRIC_DIMENSION_VALUES)[] };

export const METRIC_DIMENSION_VALUES = Object.freeze({
  environment: ["LOCAL_SYNTHETIC", "LOCAL_WRANGLER", "STAGING", "PRODUCTION"],
  consumer_kind: ["HUMAN_HTTP", "MCP", "PI"],
  operation: ["SEARCH", "NODE", "NEIGHBORS", "CALLERS", "CALLEES", "PATH", "SOURCES"],
  window_days: ["7", "30", "90"],
  route_family: ["API", "ARTIFACT", "CONTEXT", "GRAPH", "MCP", "SYNC"],
  status_class: ["2XX", "3XX", "4XX", "5XX"],
  study_protocol: ["CONTEXT_RELEVANCE_V1", "CONNECT_V1", "ONBOARD_V1", "MANUAL_PASTE_V1"],
  operation_class: ["READ", "WRITE", "QUERY"],
  object_class: ["ARTIFACT", "GRAPH", "SNAPSHOT", "ORPHAN"],
  workflow: ["CI", "GRAPHIFY"],
  cache_state: ["HIT", "MISS", "UNKNOWN"],
  device_class: ["DESKTOP", "MOBILE"],
  project_count_band: ["1", "2_TO_5", "6_TO_20"],
  command: ["CONNECT", "STATUS", "SYNC", "SEARCH", "GRAPH", "SNAPSHOT"],
} as const);

const metric = (definition: BaseMetric) => Object.freeze(definition);
const projectWindow = Object.freeze(["environment", "window_days"] as const);
const localEnvironment = Object.freeze(["environment"] as const);
const livePlatform = Object.freeze(["environment", "route_family", "status_class"] as const);

const BASE_METRICS = Object.freeze([
  metric({
    id: "CTX-001",
    name: "Context tokens per task",
    formula: "sum(response.tokenEstimate) / completed measured tasks",
    unit: "estimated tokens/task",
    inclusion: "Human/MCP Context Engine search responses assigned to a consented study task",
    exclusion: "Transport/schema tokens, retries, failed/denied requests, unassigned calls",
    source: "Response-local ContextResult.tokenEstimate plus manual task sheet",
    privacy: "participant study; aggregate only",
    dimensions: ["environment", "consumer_kind"],
    retention: "Raw task sheet 30 days; aggregate 13 months after approval",
    collection: "Manual study export; no in-product persistence",
    baseline: "Local synthetic Context Engine samples only; not production",
    target: "Establish production baseline, then reduce without relevance regression",
    threshold:
      "Review at 70/85/95% of maxTokens budget; action is investigate/reduce/fail acceptance",
    cadence: "Per launch study, then quarterly",
    owner: "Product",
    status: "MANUAL_STUDY",
  }),
  metric({
    id: "CTX-002",
    name: "Irrelevant-context ratio",
    formula: "reviewer-marked irrelevant returned sources / all returned sources reviewed",
    unit: "ratio",
    inclusion: "Consent-based blinded review of complete bounded response source lists",
    exclusion: "Truncated omitted sources, source errors, unreviewed tasks",
    source: "Manual relevance rubric joined only to response-local source ordinal",
    privacy: "participant study; no query/content retained",
    dimensions: ["environment", "consumer_kind"],
    retention: "De-identified ratings 13 months; source text and query not retained",
    collection: "Manual study",
    baseline: "None; local synthetic fixtures cannot establish relevance",
    target: "<=0.15 with >=30 tasks and two reviewers",
    threshold: ">0.21 investigate; >0.30 stop launch; no 95% quota threshold applies",
    cadence: "Before launch and quarterly",
    owner: "Product",
    status: "MANUAL_STUDY",
  }),
  metric({
    id: "CTX-003",
    name: "Graph response size",
    formula: "sum(exact UTF-8 serialized graph result bytes) / successful graph responses",
    unit: "bytes/response",
    inclusion: "Successful human and MCP graph query result envelopes",
    exclusion: "Raw stored graph bytes, denied/error envelopes",
    source: "Response-local serialization; local audit uses production queryGraph",
    privacy: "aggregate operational",
    dimensions: ["environment", "operation", "consumer_kind"],
    retention: "No raw records; local evidence retained in Git; live aggregate 30 days if approved",
    collection: "Local audit; live Worker Analytics/log metric blocked",
    baseline: "Local synthetic sample emitted by audit:metrics",
    target: "<=128 KiB MCP envelope; <=256 KiB human projection design ceiling; <=25 records",
    threshold: "70/85/95% of 128 KiB => 91,750/111,411/124,518 bytes",
    cadence: "Every release locally; weekly live",
    owner: "API",
    status: "MEASURED_LOCAL",
  }),
  metric({
    id: "CTX-004",
    name: "Artifact retrieval size",
    formula: "sum(exact returned artifact content bytes) / successful artifact retrievals",
    unit: "bytes/response",
    inclusion: "Successful bounded HTTP/MCP artifact content reads",
    exclusion: "Metadata-only reads, denied/errors, R2 HEAD bytes",
    source: "Response-local encoded content; production MCP_LIMITS",
    privacy: "aggregate operational",
    dimensions: ["environment", "consumer_kind"],
    retention: "No raw records; aggregate 30 days if approved",
    collection: "Local limit audit; live metric blocked",
    baseline: "Production maximum derived locally",
    target: "<=1 MiB HTTP and <=48 KiB MCP per response",
    threshold: "70/85/95% of applicable production bound",
    cadence: "Every release locally; weekly live",
    owner: "API",
    status: "MEASURED_LOCAL",
  }),
  metric({
    id: "REL-001",
    name: "Graph build success rate",
    formula: "terminal PUBLISHED attempts / (terminal PUBLISHED + FAILED + CLEANED attempts)",
    unit: "ratio",
    inclusion: "Attempts terminal in selected half-open UTC window",
    exclusion:
      "QUEUED/BUILDING, legacy rows without exact attempt outcome, retries counted as separate attempts",
    source: "D1 graph_build_attempts and trigger-derived project audit",
    privacy: "project operational",
    dimensions: projectWindow,
    retention:
      "Underlying immutable metadata indefinite under current policy; API windows <=90 days",
    collection: "GET project metrics aggregate",
    baseline: "Null until project has terminal attempts",
    target: ">=0.95 over >=20 attempts",
    threshold: "Investigate <0.95; freeze new builds <0.85; stop launch <0.70",
    cadence: "Weekly and before launch",
    owner: "Graph",
    status: "DERIVABLE",
  }),
  metric({
    id: "REL-002",
    name: "Sync success rate",
    formula: "SYNC_SUCCEEDED reports / (SYNC_SUCCEEDED + SYNC_FAILED reports)",
    unit: "ratio",
    inclusion: "Terminal sync reports in selected half-open UTC window",
    exclusion: "STATUS reports, clients that do not report, rejected/unauthorized reports",
    source: "D1 sync_state_events via project audit materialization",
    privacy: "project operational",
    dimensions: projectWindow,
    retention: "Immutable audit metadata indefinite; API windows <=90 days",
    collection: "GET project metrics aggregate",
    baseline: "Null until reports exist; coverage count always returned",
    target: ">=0.95 over >=20 reports",
    threshold: "Investigate <0.95; freeze rollout <0.85; stop launch <0.70",
    cadence: "Weekly and before launch",
    owner: "Client",
    status: "DERIVABLE",
  }),
  metric({
    id: "REL-003",
    name: "Failed-update preservation",
    formula:
      "failed update probes retaining byte-identical prior valid cache / all failed update probes",
    unit: "ratio",
    inclusion: "Controlled local/E2E corrupt, interrupted, and transport-failure probes",
    exclusion: "Normal successful sync, unverified preexisting cache",
    source: "CLI mutation tests and local E2E cache-safety assertion",
    privacy: "synthetic test",
    dimensions: localEnvironment,
    retention: "Git/test receipts",
    collection: "Executable tests; no user telemetry",
    baseline: "Local test evidence only",
    target: "1.00",
    threshold: "Any failure blocks release",
    cadence: "Every release",
    owner: "Client",
    status: "MEASURED_LOCAL",
  }),
  metric({
    id: "REL-004",
    name: "Artifact conflict rate",
    formula:
      "authorized artifact version 409 conflicts / authorized artifact version mutation attempts",
    unit: "ratio",
    inclusion: "Known-project version CAS attempts",
    exclusion: "Authorization/validation failures and archive conflicts",
    source: "Would require approved redacted edge aggregate; D1 retains successes only",
    privacy: "project operational",
    dimensions: ["environment", "route_family"],
    retention: "Not collected",
    collection: "No new persistence; live aggregate design approval required",
    baseline: "None",
    target: "Observe baseline; investigate workflow if >0.10",
    threshold: "70/85/95 review bands unavailable until baseline",
    cadence: "Weekly after approval",
    owner: "Product/API",
    status: "NOT_COLLECTED",
  }),
  metric({
    id: "REL-005",
    name: "API error rate",
    formula: "5xx Worker responses / all Worker API responses",
    unit: "ratio",
    inclusion: "Production Worker API routes",
    exclusion: "Pages assets, 4xx client/auth outcomes, synthetic health traffic",
    source: "Cloudflare Workers Analytics by route family/status",
    privacy: "platform aggregate",
    dimensions: livePlatform,
    retention: "Provider aggregate per approved plan; export summary 13 months",
    collection: "External analytics receipt; never request logs",
    baseline: "Unavailable without deployment",
    target: "<0.01",
    threshold: "Investigate >=0.01; incident >=0.03; stop launch >=0.05",
    cadence: "Daily during launch, weekly steady state",
    owner: "Platform",
    status: "BLOCKED_LIVE",
  }),
  metric({
    id: "REL-006",
    name: "Graph failure count",
    formula: "count terminal FAILED and CLEANED graph attempts",
    unit: "failures/window",
    inclusion: "FAILED and retained CLEANED attempts by failed_at in selected half-open UTC window",
    exclusion: "Denied commands and nonterminal builds",
    source: "D1 graph_build_attempts/project audit",
    privacy: "project operational",
    dimensions: projectWindow,
    retention: "Immutable metadata indefinite; API windows <=90 days",
    collection: "GET project metrics aggregate",
    baseline: "Zero or exact derived count",
    target: "0; interpret with REL-001 denominator",
    threshold: "Any failure investigate; >=3/week freeze new builds",
    cadence: "Weekly",
    owner: "Graph",
    status: "DERIVABLE",
  }),
  metric({
    id: "REL-007",
    name: "Sync failure count",
    formula: "count SYNC_FAILED reports",
    unit: "failures/window",
    inclusion: "Accepted failed sync reports in selected half-open UTC window",
    exclusion: "Reporting failures, rejected reports, offline use without a report",
    source: "D1 sync_state_events/project audit",
    privacy: "project operational",
    dimensions: projectWindow,
    retention: "Immutable metadata indefinite; API windows <=90 days",
    collection: "GET project metrics aggregate",
    baseline: "Zero or exact derived count with coverage caveat",
    target: "0; interpret with REL-002 denominator",
    threshold: "Any repeated client failure investigate; >=3/week freeze rollout",
    cadence: "Weekly",
    owner: "Client",
    status: "DERIVABLE",
  }),
  metric({
    id: "REL-008",
    name: "Graph duration",
    formula: "published_at or failed_at - claimed_at for terminal graph attempts",
    unit: "milliseconds; avg/min/max/sample count",
    inclusion: "PUBLISHED, FAILED, and CLEANED attempts terminal in selected half-open window",
    exclusion: "Queue time, nonterminal, legacy no-attempt graphs, Actions setup outside claim",
    source: "D1 graph_build_attempts",
    privacy: "project operational",
    dimensions: projectWindow,
    retention: "Immutable metadata indefinite; API windows <=90 days",
    collection: "GET project metrics aggregate; representative Actions benchmark separately",
    baseline: "Null until terminal samples",
    target: "Representative p95 <20 minutes and hard workflow <30 minutes",
    threshold: "70/85/95% workflow cap => 21/25.5/28.5 minutes",
    cadence: "Per build and weekly",
    owner: "Graph/Platform",
    status: "DERIVABLE",
  }),
  metric({
    id: "DX-001",
    name: "Time to connect project",
    formula: "task completion timestamp - study start timestamp",
    unit: "minutes/task",
    inclusion: "Consented first project create+Git connect study",
    exclusion: "Provider outage/waiting periods reported separately",
    source: "Facilitated study stopwatch",
    privacy: "participant study aggregate",
    dimensions: ["environment", "study_protocol"],
    retention: "De-identified durations 13 months; notes 30 days",
    collection: "Manual study",
    baseline: "No valid participant baseline",
    target: "median <=5 minutes; p85 <=10 minutes",
    threshold: "p70/p85/p95 reported; p95 >15 minutes blocks UX acceptance",
    cadence: "Before launch and major onboarding changes",
    owner: "Product",
    status: "MANUAL_STUDY",
  }),
  metric({
    id: "DX-002",
    name: "Time to onboard developer",
    formula: "successful context search timestamp - invitation task start timestamp",
    unit: "minutes/task",
    inclusion: "Consented invite accept, local connect/sync, first search study",
    exclusion: "Unrelated environment install time reported separately",
    source: "Facilitated study stopwatch",
    privacy: "participant study aggregate",
    dimensions: ["environment", "study_protocol"],
    retention: "De-identified durations 13 months; notes 30 days",
    collection: "Manual study",
    baseline: "No valid participant baseline",
    target: "median <=10 minutes; p85 <=20 minutes",
    threshold: "p70/p85/p95 reported; p95 >30 minutes blocks UX acceptance",
    cadence: "Before launch and major onboarding changes",
    owner: "Product",
    status: "MANUAL_STUDY",
  }),
  metric({
    id: "DX-003",
    name: "Manual context-paste actions avoided",
    formula: "self-reported comparable paste count before - paste count during study task",
    unit: "paste actions/task",
    inclusion: "Consented comparable task pairs with explicit rubric",
    exclusion: "Clipboard telemetry, inferred keystrokes, uncompared tasks",
    source: "Participant task sheet",
    privacy: "participant study; aggregate only",
    dimensions: ["environment", "study_protocol"],
    retention: "De-identified counts 13 months; no clipboard data",
    collection: "Manual study; never instrument clipboard",
    baseline: "None",
    target: "median >=1 avoided action/task without lower task success",
    threshold: "p70/p85/p95 distribution; median <=0 triggers product review",
    cadence: "Before launch and quarterly",
    owner: "Product",
    status: "MANUAL_STUDY",
  }),
  metric({
    id: "INF-001",
    name: "Worker requests per project",
    formula: "project-attributed Worker requests / active projects in same UTC period",
    unit: "requests/project/day",
    inclusion:
      "Production project-scoped Worker requests and explicitly allocated multi-project calls",
    exclusion: "Public auth/health/global routes unless separately reported; Pages assets",
    source: "Cloudflare Workers Analytics; allocation policy must be approved",
    privacy: "platform aggregate",
    dimensions: ["environment", "route_family"],
    retention: "External daily aggregate 13 months",
    collection: "External analytics receipt; D1 must not claim this",
    baseline: "Unavailable without deployment",
    target: "Stay within account-shared free-tier budget",
    threshold: "Account 70k/85k/95k of current 100k requests/day",
    cadence: "Daily/weekly",
    owner: "Platform",
    status: "BLOCKED_LIVE",
  }),
  metric({
    id: "INF-002",
    name: "D1 rows and operations per project",
    formula: "attributed rows read, rows written, and queries / active projects",
    unit: "rows or operations/project/day",
    inclusion: "Production D1 analytics/query insights",
    exclusion: "Returned-row counts, local SQLite rows, inferred code statement counts",
    source: "Cloudflare D1 analytics/query insights",
    privacy: "platform aggregate",
    dimensions: ["environment", "operation_class"],
    retention: "External daily aggregate 13 months",
    collection: "External analytics receipt",
    baseline: "Unavailable without remote D1",
    target: "Stay within account-shared free-tier budget",
    threshold: "Rows read 3.5M/4.25M/4.75M; rows written 70k/85k/95k daily",
    cadence: "Daily/weekly",
    owner: "Platform",
    status: "BLOCKED_LIVE",
  }),
  metric({
    id: "INF-003",
    name: "R2 storage and operations per project",
    formula: "project-prefix inventory bytes and attributable Class A/B operations",
    unit: "bytes/project and operations/project/month",
    inclusion: "Private Standard bucket inventory and platform operations",
    exclusion: "D1-known referenced bytes as billed truth; unknown orphans",
    source: "R2 inventory/analytics; D1 route separately reports known referenced bytes",
    privacy: "platform aggregate",
    dimensions: ["environment", "object_class", "operation_class"],
    retention: "External monthly aggregate 13 months",
    collection: "External receipt plus project metrics metadata",
    baseline: "D1-known referenced bytes derivable; actual billed storage blocked",
    target: "Stay within account-shared free-tier budget",
    threshold: "Storage 7/8.5/9.5 GB-month; A 700k/850k/950k; B 7M/8.5M/9.5M",
    cadence: "Weekly/monthly",
    owner: "Platform",
    status: "BLOCKED_LIVE",
  }),
  metric({
    id: "INF-004",
    name: "Actions minutes per project",
    formula: "sum workflow billed duration allocated by exact project input",
    unit: "minutes/project/month",
    inclusion: "Quality allocation policy and Graphify runs",
    exclusion: "Local runs; self-hosted wall time represented as billed GitHub minutes",
    source: "GitHub Actions billing and workflow run analytics",
    privacy: "platform aggregate",
    dimensions: ["environment", "workflow"],
    retention: "External monthly aggregate 13 months",
    collection: "External receipt",
    baseline:
      "Unavailable; self-hosted Graphify may bill zero GitHub minutes but has operator cost",
    target: "Stay within owner plan; Graphify hard cap 30 minutes/run",
    threshold: "Private hosted account 1,400/1,700/1,900 of current 2,000 minutes/month",
    cadence: "Monthly and before launch",
    owner: "Platform",
    status: "BLOCKED_LIVE",
  }),
  metric({
    id: "PERF-001",
    name: "Dashboard performance",
    formula: "p50/p70/p85/p95 navigation-to-complete Overview render duration",
    unit: "milliseconds",
    inclusion: "Normal cached deployed browser Overview loads",
    exclusion: "First auth/provider flow and synthetic Node handler timing",
    source: "Approved privacy-safe browser/manual live test",
    privacy: "aggregate performance",
    dimensions: ["environment", "cache_state", "device_class"],
    retention: "Aggregate 30 days",
    collection: "Live browser study; no third-party analytics",
    baseline: "Not reproducibly measurable in current non-browser harness",
    target: "p95 <2000 ms",
    threshold: "1400/1700/1900 ms (70/85/95% target)",
    cadence: "Before launch and each web release",
    owner: "Web",
    status: "BLOCKED_LIVE",
  }),
  metric({
    id: "PERF-002",
    name: "Artifact metadata performance",
    formula: "p50/p70/p85/p95 request wall duration for metadata routes",
    unit: "milliseconds",
    inclusion: "Deployed successful artifact list/detail metadata requests",
    exclusion: "Content download and provider wait",
    source: "Cloudflare Workers Analytics",
    privacy: "platform aggregate",
    dimensions: livePlatform,
    retention: "Aggregate 30 days",
    collection: "External analytics receipt",
    baseline: "Unavailable without deployment",
    target: "p95 <500 ms (near-instant operational definition)",
    threshold: "350/425/475 ms",
    cadence: "Weekly and before launch",
    owner: "API",
    status: "BLOCKED_LIVE",
  }),
  metric({
    id: "PERF-003",
    name: "Context retrieval performance",
    formula: "p50/p70/p85/p95 wall duration plus exact byte/token/source distributions",
    unit: "milliseconds and bounded response units",
    inclusion: "Successful deployed Context Engine searches",
    exclusion: "Denied/error calls; content/query never retained",
    source: "Response-local counters plus Workers Analytics",
    privacy: "aggregate operational",
    dimensions: ["environment", "consumer_kind", "project_count_band"],
    retention: "Aggregate 30 days",
    collection: "Bounds measured locally; latency blocked live",
    baseline: "Local exact sizes only; not production latency",
    target: "100% within requested bytes/tokens/sources; live p95 established before SLA",
    threshold: "Any bound breach blocks; latency p70/p85/p95 reviewed after baseline",
    cadence: "Every release locally; weekly live",
    owner: "Context/API",
    status: "MEASURED_LOCAL",
  }),
  metric({
    id: "PERF-004",
    name: "Local graph query performance",
    formula:
      "p50/p70/p85/p95 monotonic duration of production queryGraph over fixed synthetic projection",
    unit: "milliseconds/query",
    inclusion: "Warm local in-process fixed fixture queries",
    exclusion: "Disk load, Worker/R2 validation, production repository claim",
    source: "audit:metrics production queryGraph benchmark",
    privacy: "synthetic test",
    dimensions: localEnvironment,
    retention: "Git evidence",
    collection: "Local audit with environment/sample size",
    baseline: "Latest local audit only; not SLA",
    target: "p95 <50 ms on audit fixture",
    threshold: "35/42.5/47.5 ms",
    cadence: "Every release",
    owner: "Graph/Client",
    status: "MEASURED_LOCAL",
  }),
  metric({
    id: "PERF-005",
    name: "Asynchronous graph update",
    formula: "user-facing requests blocked on graph generation / graph reservations",
    unit: "ratio",
    inclusion: "Graph reservation/build flows",
    exclusion: "Explicit status reads and publication calls",
    source: "Architecture route/process audit plus live correlation",
    privacy: "aggregate operational",
    dimensions: ["environment"],
    retention: "Git evidence; live aggregate 30 days",
    collection: "Local architecture evidence; live confirmation blocked",
    baseline: "Local route architecture executes Graphify outside Worker",
    target: "0",
    threshold: "Any user request executing Graphify blocks release",
    cadence: "Every release and live launch",
    owner: "Graph/API",
    status: "MEASURED_LOCAL",
  }),
  metric({
    id: "PERF-006",
    name: "Nonblocking sync",
    formula: "normal Pi commands blocked by background sync / normal Pi commands",
    unit: "ratio",
    inclusion: "Explicit Pi lifecycle scenarios while sync unavailable/running",
    exclusion: "User-invoked sync command itself",
    source: "Pi/CLI local tests; live host study",
    privacy: "synthetic/live aggregate",
    dimensions: ["environment", "command"],
    retention: "Git evidence; live aggregate 30 days",
    collection: "Local tests and live host acceptance",
    baseline: "Local explicit-command architecture only",
    target: "0; verified local graph remains usable",
    threshold: "Any blocked unrelated command blocks launch",
    cadence: "Every client release",
    owner: "Client",
    status: "MEASURED_LOCAL",
  }),
  metric({
    id: "PERF-007",
    name: "Pi performance",
    formula: "p50/p70/p85/p95 command dispatch-to-bounded-notification duration",
    unit: "milliseconds/command",
    inclusion: "Pinned live Pi connect/status/search/graph commands",
    exclusion: "Model inference (none required), terminal paint after notification",
    source: "Approved live Pi host harness",
    privacy: "aggregate performance",
    dimensions: ["environment", "command"],
    retention: "Aggregate 30 days",
    collection: "Live client acceptance; no third-party telemetry",
    baseline: "Package tests/token audit are not live performance",
    target: "Local status/graph p95 <500 ms; online commands separately baseline network",
    threshold: "350/425/475 ms for local commands; online p70/p85/p95 reviewed",
    cadence: "Before launch and each Pi release",
    owner: "Client",
    status: "BLOCKED_LIVE",
  }),
] satisfies readonly BaseMetric[]);

const FORMULA_PARTS: Record<string, readonly [string, string, string]> = {
  "CTX-001": ["sum response tokenEstimate", "completed measured tasks", "consented study task"],
  "CTX-002": [
    "reviewer-marked irrelevant returned sources",
    "all reviewed returned sources",
    "consented study",
  ],
  "CTX-003": [
    "sum exact UTF-8 serialized graph-result bytes",
    "successful graph responses",
    "response-local",
  ],
  "CTX-004": [
    "sum exact returned artifact-content bytes",
    "successful artifact retrievals",
    "response-local",
  ],
  "REL-001": [
    "terminal PUBLISHED attempts",
    "terminal PUBLISHED + FAILED + CLEANED attempts",
    "selected half-open UTC window",
  ],
  "REL-002": [
    "SYNC_SUCCEEDED reports",
    "SYNC_SUCCEEDED + SYNC_FAILED reports",
    "selected half-open UTC window",
  ],
  "REL-003": [
    "failed probes preserving the byte-identical prior valid cache",
    "all controlled failed-update probes",
    "release test run",
  ],
  "REL-004": [
    "authorized artifact version 409 conflicts",
    "authorized artifact version mutation attempts",
    "approved live reporting window",
  ],
  "REL-005": [
    "5xx Worker API responses",
    "all Worker API responses",
    "provider UTC reporting period",
  ],
  "REL-006": [
    "terminal FAILED + CLEANED graph attempts",
    "not applicable",
    "selected half-open UTC window",
  ],
  "REL-007": ["accepted SYNC_FAILED reports", "not applicable", "selected half-open UTC window"],
  "REL-008": [
    "terminal timestamp minus claimed_at per PUBLISHED, FAILED, or CLEANED attempt",
    "terminal attempt sample count",
    "selected half-open UTC window",
  ],
  "DX-001": [
    "sum connect-task elapsed minutes",
    "completed connect tasks",
    "consented CONNECT_V1 study",
  ],
  "DX-002": [
    "sum onboarding-task elapsed minutes",
    "completed onboarding tasks",
    "consented ONBOARD_V1 study",
  ],
  "DX-003": [
    "sum comparable before-study paste count minus study paste count",
    "completed comparable task pairs",
    "consented MANUAL_PASTE_V1 study",
  ],
  "INF-001": [
    "project-attributed Worker requests",
    "active projects in the same UTC period",
    "provider UTC day",
  ],
  "INF-002": [
    "attributed D1 rows read, rows written, and queries",
    "active projects in the same UTC period",
    "provider UTC day",
  ],
  "INF-003": [
    "project-prefix inventory bytes and attributable Class A/B operations",
    "project",
    "provider billing month",
  ],
  "INF-004": [
    "workflow billed minutes allocated by exact project input",
    "project",
    "provider billing month",
  ],
  "PERF-001": [
    "navigation-to-complete Overview durations",
    "successful measured Overview loads",
    "approved browser run",
  ],
  "PERF-002": [
    "artifact metadata request wall durations",
    "successful measured metadata requests",
    "provider UTC reporting period",
  ],
  "PERF-003": [
    "Context request wall durations and exact byte/token/source counters",
    "successful Context searches",
    "local run or provider UTC period",
  ],
  "PERF-004": [
    "production queryGraph monotonic durations",
    "2,000 measured calls after fixed warmup",
    "one labeled local synthetic run",
  ],
  "PERF-005": [
    "user-facing requests blocked on graph generation",
    "graph reservations",
    "release architecture check",
  ],
  "PERF-006": [
    "normal Pi commands blocked by background sync",
    "normal Pi commands in controlled scenarios",
    "client release run",
  ],
  "PERF-007": [
    "Pi dispatch-to-bounded-notification durations",
    "successful measured commands",
    "approved live Pi run",
  ],
};

export const PLAYBOOK_METRIC_SOURCES = Object.freeze([
  "Playbook §36: average context tokens per task",
  "Playbook §36: irrelevant context ratio",
  "Playbook §36: Graphify response size",
  "Playbook §36: artifact retrieval size",
  "Playbook §36: graph build success rate",
  "Playbook §36: sync success rate",
  "Playbook §36: failed update preservation",
  "Playbook §36: artifact conflict rate",
  "Playbook §36: time to connect project",
  "Playbook §36: time to onboard developer",
  "Playbook §36: manual context-paste actions avoided",
  "Playbook §36: Worker requests/project",
  "Playbook §36: D1 reads/writes/project",
  "Playbook §36: R2 storage/project",
  "Playbook §36: GitHub Actions minutes/project",
]);

export const ARCHITECTURE_REQUIREMENT_SOURCE_BY_ID = Object.freeze({
  "REL-005": "Technical Architecture §32 Observability: API error rate",
  "REL-006": "Technical Architecture §32 Observability: Graph failure count",
  "REL-007": "Technical Architecture §32 Observability: Sync failure count",
  "REL-008": "Technical Architecture §32 Observability: Graph duration",
  "PERF-001": "Technical Architecture §33 Performance Goals: Dashboard performance",
  "PERF-002": "Technical Architecture §33 Performance Goals: Artifact metadata performance",
  "PERF-003": "Technical Architecture §33 Performance Goals: Context retrieval performance",
  "PERF-004": "Technical Architecture §33 Performance Goals: Local graph query performance",
  "PERF-005": "Technical Architecture §33 Performance Goals: Asynchronous graph generation",
  "PERF-006": "Technical Architecture §33 Performance Goals: Nonblocking sync",
  "PERF-007": "Technical Architecture §33 Performance Goals: Pi performance",
});

const REQUIREMENT_SOURCE_BY_ID: Record<string, readonly string[]> = Object.fromEntries([
  ...BASE_METRICS.slice(0, 4).map((item, index) => [
    item.id,
    [PLAYBOOK_METRIC_SOURCES[index], "PRD §36 Product Success Metrics"],
  ]),
  ...BASE_METRICS.slice(4, 8).map((item, index) => [
    item.id,
    [PLAYBOOK_METRIC_SOURCES[index + 4], "PRD §36 Product Success Metrics"],
  ]),
  ...BASE_METRICS.slice(12, 15).map((item, index) => [
    item.id,
    [PLAYBOOK_METRIC_SOURCES[index + 8], "PRD §36 Product Success Metrics"],
  ]),
  ...BASE_METRICS.slice(15, 19).map((item, index) => [
    item.id,
    [PLAYBOOK_METRIC_SOURCES[index + 11], "PRD §36 Product Success Metrics"],
  ]),
  ...Object.entries(ARCHITECTURE_REQUIREMENT_SOURCE_BY_ID).map(([id, source]) => [
    id,
    [source, "Technical Architecture §35 Acceptance Criteria"],
  ]),
]);

export const METRICS = Object.freeze(
  BASE_METRICS.map((item): MetricDefinition => {
    const parts = FORMULA_PARTS[item.id];
    const requirementSources = REQUIREMENT_SOURCE_BY_ID[item.id];
    if (!parts || !requirementSources)
      throw new Error(`missing canonical metric metadata: ${item.id}`);
    return Object.freeze({
      ...item,
      numerator: parts[0],
      denominator: parts[1],
      window: parts[2],
      dimensions: Object.freeze(
        item.dimensions.map((key) => Object.freeze({ key, values: METRIC_DIMENSION_VALUES[key] })),
      ),
      requirementSources: Object.freeze(requirementSources),
    });
  }),
);
