export const PROJECT_AUDIT_ACTIONS = [
  "PROJECT_CREATED",
  "PROJECT_SETTINGS_UPDATED",
  "ARTIFACT_CREATED",
  "ARTIFACT_VERSION_CREATED",
  "ARTIFACT_ARCHIVED",
  "GIT_CONNECTED",
  "GIT_SYNCED",
  "GIT_DISCONNECTED",
  "MEMBER_INVITED",
  "INVITATION_ACCEPTED",
  "INVITATION_REVOKED",
  "MEMBER_ROLE_CHANGED",
  "MEMBER_REMOVED",
  "GRAPH_BUILD_RESERVED",
  "GRAPH_CLAIMED",
  "GRAPH_PUBLISHED",
  "GRAPH_FAILED",
  "SNAPSHOT_CREATED",
  "SNAPSHOT_CREATE_REJECTED",
  "SNAPSHOT_CREATE_FAILED",
  "SYNC_STATE_REPORTED",
  "MACHINE_CREDENTIAL_ISSUED",
  "MACHINE_CREDENTIAL_ROTATED",
  "MACHINE_CREDENTIAL_REVOKED",
  "MCP_CREDENTIAL_ISSUED",
  "MCP_CREDENTIAL_ROTATED",
  "MCP_CREDENTIAL_REVOKED",
  "MCP_REQUEST",
] as const;

export type ProjectAuditAction = (typeof PROJECT_AUDIT_ACTIONS)[number];

const PROJECT_AUDIT_ACTION_SET: ReadonlySet<string> = new Set(PROJECT_AUDIT_ACTIONS);

export function isProjectAuditAction(value: string): value is ProjectAuditAction {
  return PROJECT_AUDIT_ACTION_SET.has(value);
}
